### YamlMime:ManagedReference
items:
- uid: Services
  commentId: N:Services
  id: Services
  children:
  - Services.Bloogs
  langs:
  - csharp
  - vb
  name: Services
  nameWithType: Services
  fullName: Services
  type: Namespace
  assemblies:
  - Services
references:
- uid: Services.Bloogs
  commentId: T:Services.Bloogs
  href: Services.Bloogs.html
  name: Bloogs
  nameWithType: Bloogs
  fullName: Services.Bloogs
